version: '3.8'
services:
  react-app:
    image: mzazakeith/yolo-app-client:1.0.0
    container_name: frontend
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - mern
    depends_on:
      - backend
  backend:
    image: mzazakeith/yolo-app-backend:1.0.0
    container_name: backend
    ports:
      - "5000:5000"
    env_file: ./.env
    environment:
      - MONGODB_URI=mongodb://admin:password@mongo:27017/yolomy?retryWrites=true&writeConcern=majority&authSource=admin
      - DB_NAME=yolomy
    networks:
      - mern
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongodb_server
    ports:
      - "27017:27017"
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    networks:
      - mern
    volumes:
      - mongo-data:/data/db
networks:
  mern:
    driver: bridge
volumes:
  mongo-data:
    driver: local
