apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: yolo-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo-db
  serviceName: yolo-db
  template:
    metadata:
      labels:
        app: yolo-db
    spec:
      containers:
        - name: yolo-db
          image: mongo:latest
          env:
            - name: DB_NAME
              value: yolomy
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: yolo-data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: yolo-data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
