apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: yolo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo-backend
  template:
    metadata:
      labels:
        app: yolo-backend
    spec:
      containers:
        - name: yolo-backend
          image: mzazakeith/yolo-app-backend:v1.0.2
          ports:
            - containerPort: 5000
          env:
            - name: USER_NAME
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-user
            - name: USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-password
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: mongo-url


