apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: yolo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo-backend
  template:
    metadata:
      labels:
        app: yolo-backend
    spec:
      containers:
        - name: backend-container
          image: mzazakeith/yolo-app-backend:v1.0.2
          ports:
            - containerPort: 5000
          env:
            - name: MONGODB_URI
              value: mongodb://yolo-db:27017
