apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: yolo-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo-client
  template:
    metadata:
      labels:
        app: yolo-client
    spec:
      containers:
        - name: client-container
          image: mzazakeith/yolo-app-client:v1.0.2
          ports:
            - containerPort: 3000
          tty: true
          stdin: true
