apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
data:
  backend.conf: |
    database:
      uri: mongodb://yolo-db:27017
    server:
      port: 5000
    security:
      enableAuth: false
